### PR TITLE
Feature/typescript support

### PR DESCRIPTION
**Pull request by guilhermetod**
Hey. First, thank you and congratulations for this tool. The the absence of live reloading was the biggest pain in developping for GAS and I was really happy to find this repo. I also checked your React Starter repo and figured that since you index your server functions in a single file, we could follow that patterns and add TypeScript support for the Gas Client, so we'll be able to check and get IDE support for function names, parameters and return types. The TypeScript functionality is done at commit 305be48. I also included some other changes and suggestions which I explain in the commit descriptions. If you accept this pull request, feel totally free to cherry pick the changes you like.

I hope you like and accept it, and thanks again for this repo!

### CODE REVIEW

**Comment by enuchi** [comment]
Hey @guilhermetod, thanks for this. Glad others are interested in improving the developer experience for GAS projects. Would be happy to include changes that help support other setups besides the React project. Getting IDE support for server function types, etc. is a great idea.

Give me a bit of time to look through more carefully -- have a few comments/questions, and want to try it out with my setup.

**Comment by guilhermetod** [comment]
Sure, I'm glad you're open for the idea. Take your time and if you need anything, just ask me.

**Comment by enuchi** [comment]
Looks like this got closed. Did you mean to close the PR @guilhermetod ?

**Comment by guilhermetod** [comment]
I'm sorry, I really didn't mean to close it. I was testing the package instalation and merged my branch with gitflow, which I forgot that automatically deletes the old branch.

I'll have it back in a couple of minutes. I made a few extra edits and fixes, would you prefer me to reopen this and make a new PR with the other changes or just open a brand new with all the changes?

**Comment by enuchi** [comment]
No problem at all. Can you include all the changes in one PR?

**Pull request closed without merging**
