### PR TITLE
v1.0.0: Feature/typescript support

### PR DESCRIPTION
**Pull request by enuchi**
Continuation of #3

### CODE REVIEW

**Comment by enuchi** [comment]
@guilhermetod opening this PR with the work you did, and made a few changes. Would like to publish this as new major version 1.0.0.

The breaking changes would be:
- Named export GASClient instead of default export
- Changing the target origin in postMessage in the proxy handler file from window.location.origin to '*' (any domain)

I also added tests to the current .js version so can track if this breaks anything else, and it seems fine.

Would love if you could try running this version with your setup and see if you have any issues.

**Comment by guilhermetod** [comment]
Nice @enuchi I'll try to run this between today and the end of the weekend. Feel free to remind me if I don't give you any feedback until sunday.

**Comment by enuchi** [comment]
Thanks and no rush. Also I published a prerelease as `1.0.0-pr.1` if you want to try installing like that.

**Comment by guilhermetod** [comment]
Hey, I tested it yesterday in my project and everything went fine. The only thing I cant point out is that I got a warn during compilation about it being a CommonJS module, but it did not impact on the functionality at all. But since it's going to be bundled and run into a browser, I think it can be published as an ES module instead.

**Comment by enuchi** [comment]
Thanks @guilhermetod - updated to publish esm instead. Do you mind testing it out with your setup? Published prelease `1.0.0-pr.2`.

**Comment by guilhermetod** [comment]
@enuchi took me a while, but I just tested now and it workd perfectly fine, no warning!

**Comment by enuchi** [comment]
Merged and published as `gas-client@1.0.0`. Thanks @guilhermetod for all your work improving this project!

**Pull request merged**
